spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

firebase:
  store:
    DB: ${FIREBASE_DB} #example
  storage:
    bucket: ${FIREBASE_BUCKET} #example-abcd.firebasestorage.app

jwt:
  secret: ${JWT_SECRET}
  access-expiration: 900000 #15min
  refresh-expiration: 604800000 #7days

